package USML.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.generator.template.PropertyMacroContext;
import USML.util.util;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import java.util.List;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import jetbrains.mps.generator.template.WeavingMappingRuleContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static boolean baseMappingRule_Condition_3946458319584749006(final BaseMappingRuleContext _context) {
    return !(Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getChildren(SNodeOperations.getAncestor(_context.getNode(), "com.mbeddr.core.modules.structure.ImplementationModule", false, false)), "com.mbeddr.core.modules.structure.GlobalConstantDeclaration")).any(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, "name") == "COMMON_DEF";
      }
    }));
  }

  public static boolean baseMappingRule_Condition_7466645974721228478(final BaseMappingRuleContext _context) {
    return (SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.IStateMachine", false, false) != null) && ((SNodeOperations.getAncestor(_context.getNode(), "USML.structure.AbstractBlock", false, false) != null) || ((SNodeOperations.getAncestor(_context.getNode(), "USML.structure.ITransition", false, false) != null))) && ((SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.AbstractBlock", false, false) == null) && ((SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.ITransition", false, false) == null))) && (SNodeOperations.getAncestor(_context.getNode(), "com.mbeddr.core.expressions.structure.AssignmentExpr", false, false) != null) && ListSequence.fromList(SNodeOperations.getDescendants(BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "com.mbeddr.core.expressions.structure.AssignmentExpr", false, false), "virtual_getLValue_329990661091846550", new Object[]{}), "com.mbeddr.core.statements.structure.LocalVarRef", true, new String[]{})).contains(_context.getNode());
  }

  public static boolean baseMappingRule_Condition_7466645974721332574(final BaseMappingRuleContext _context) {
    return (SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.IStateMachine", false, false) != null) && ((SNodeOperations.getAncestor(_context.getNode(), "USML.structure.AbstractBlock", false, false) != null) || ((SNodeOperations.getAncestor(_context.getNode(), "USML.structure.ITransition", false, false) != null))) && ((SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.AbstractBlock", false, false) == null) && ((SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.ITransition", false, false) == null)));
  }

  public static Object propertyMacro_GetPropertyValue_1054945346933275900(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(SLinkOperations.getTarget(_context.getNode(), "arg", false)) + "";
  }

  public static Object propertyMacro_GetPropertyValue_130687814474693174(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_8607120610939088842(final PropertyMacroContext _context) {
    return _context.createUniqueName("_sm_terminate_", null);
  }

  public static Object propertyMacro_GetPropertyValue_130687814474693182(final PropertyMacroContext _context) {
    return util.genEventEnumName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_130687814474728633(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_130687814474728641(final PropertyMacroContext _context) {
    return util.genStateEnumName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_3946458319585710755(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object propertyMacro_GetPropertyValue_3946458319588193030(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "__" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_130687814474772691(final PropertyMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_3372386639991343431(final PropertyMacroContext _context) {
    return util.genMessageListName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_7466645974718512710(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_4306907833975213498(final PropertyMacroContext _context) {
    return util.genBigStepFunctionName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_3946458319587533114(final PropertyMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3946458319589585284(final PropertyMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3946458319593005780(final PropertyMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3587558110351009977(final PropertyMacroContext _context) {
    return "init_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3587558110351010144(final PropertyMacroContext _context) {
    return "init_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974685590938(final PropertyMacroContext _context) {
    return "action__" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3946458319585473083(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_3946458319585473096(final PropertyMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_3946458319584312299(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_3946458319584596494(final PropertyMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974709644098(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974716176004(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_3946458319593691714(final PropertyMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_3946458319593780700(final PropertyMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974712628439(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974703177068(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974718363454(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_2041445662508347162(final PropertyMacroContext _context) {
    return util.genSMStartFunctionName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735717929(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735725051(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_source_2486662774780451176", new Object[]{}), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735732113(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735856044(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735856052(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_source_2486662774780451176", new Object[]{}), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_7466645974735856062(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_qualifiedName_5470497459578244269", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_3946458319598604877(final PropertyMacroContext _context) {
    return ListSequence.fromList(SNodeOperations.getDescendants(SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IStateMachine", false, false), "USML.structure.IEvent", false, new String[]{})).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_8607120610932337992(final PropertyMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_8607120610930665035(final PropertyMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_8607120610931514207(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(_context.getNode()) + "";
  }

  public static Object propertyMacro_GetPropertyValue_6727232360811511176(final PropertyMacroContext _context) {
    return _context.createUniqueName("sm_thread", null);
  }

  public static Object propertyMacro_GetPropertyValue_7466645974728471169(final PropertyMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).count() + "";
  }

  public static Object propertyMacro_GetPropertyValue_7466645974728471272(final PropertyMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object propertyMacro_GetPropertyValue_7466645974728471318(final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(_context.getNode()) + "";
  }

  public static Object referenceMacro_GetReferent_3465079989156703615(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "arg", false), "USML.structure.IEvent", false, false), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974721329049(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "__" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "var", false), "name");

  }

  public static Object referenceMacro_GetReferent_7466645974721334760(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(SLinkOperations.getTarget(_context.getNode(), "var", false), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "__" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "var", false), "name");
  }

  public static Object referenceMacro_GetReferent_130687814474750162(final ReferenceMacroContext _context) {
    return util.genStateEnumName(BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IStateMachine", false, false), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3372386639991366805(final ReferenceMacroContext _context) {
    return util.genMessageListName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974718512811(final ReferenceMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3372386639991365756(final ReferenceMacroContext _context) {
    return util.genMessageListName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319597435891(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_initState_4306907833977380124", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3946458319597368146(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object referenceMacro_GetReferent_3946458319588330455(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "__" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object referenceMacro_GetReferent_3946458319597715052(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_initState_4306907833977380124", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3946458319597848559(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3946458319598022286(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3587558110351009823(final ReferenceMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IStateMachine", false, false), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3587558110351009872(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "__" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object referenceMacro_GetReferent_3587558110353555833(final ReferenceMacroContext _context) {
    return "init_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3587558110351010126(final ReferenceMacroContext _context) {
    return "init_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3587558110354806813(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974687493982(final ReferenceMacroContext _context) {
    return util.genMessageListName(BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IStateMachine", false, false), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974709644086(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974715904683(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object referenceMacro_GetReferent_7466645974716039890(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319587044925(final ReferenceMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319587068899(final ReferenceMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974727799841(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974727866961(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974727799862(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974727933958(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319590768164(final ReferenceMacroContext _context) {
    return "init_" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974716747491(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object referenceMacro_GetReferent_7466645974716967865(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974718207627(final ReferenceMacroContext _context) {
    return util.genSMStructName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974712628427(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974703177056(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_7466645974718363430(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object referenceMacro_GetReferent_7466645974718363441(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_8607120610935674553(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.GetEventBinding")).first(), "cbinding", true), "var", false);
  }

  public static Object referenceMacro_GetReferent_8607120610939267658(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "terminate_event");
  }

  public static Object referenceMacro_GetReferent_3946458319585298769(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319585563336(final ReferenceMacroContext _context) {
    return util.genPresentEventArrayName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object referenceMacro_GetReferent_3946458319586871013(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3946458319586883887(final ReferenceMacroContext _context) {
    return util.genSMInfoName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{})) + "_shadow";
  }

  public static Object referenceMacro_GetReferent_8607120610939153885(final ReferenceMacroContext _context) {
    return util.genBigStepFunctionName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3174948071968898920(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3174948071968895839(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object referenceMacro_GetReferent_7466645974735703016(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object referenceMacro_GetReferent_7466645974735707217(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_source_2486662774780451176", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735712334(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735740992(final ReferenceMacroContext _context) {
    return "action__" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735750122(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3946458319598746786(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_triggers_2486662774780450416", new Object[]{})).first(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735856009(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object referenceMacro_GetReferent_7466645974735856024(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_source_2486662774780451176", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735856034(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735856072(final ReferenceMacroContext _context) {
    return "action__" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_7466645974735856082(final ReferenceMacroContext _context) {
    return "on_entry_" + BehaviorReflection.invokeVirtual(String.class, BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_target_2486662774780451200", new Object[]{}), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3465079989160578792(final ReferenceMacroContext _context) {
    return util.genEventEnumName(BehaviorReflection.invokeVirtual(String.class, SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IStateMachine", false, false), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_3372386639991948245(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_3174948071968844886(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}) + "____cur_state";
  }

  public static Object referenceMacro_GetReferent_8607120610930873034(final ReferenceMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object referenceMacro_GetReferent_8607120610928009792(final ReferenceMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object referenceMacro_GetReferent_8607120610928633898(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(_context.getNode(), "event", false), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static Object referenceMacro_GetReferent_6727232360811514525(final ReferenceMacroContext _context) {
    return util.genSMStartFunctionName(BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_id_3372386639989961954", new Object[]{}));
  }

  public static Object referenceMacro_GetReferent_6727232360810761122(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "sm_ref", false), "terminate_event");
  }

  public static Object referenceMacro_GetReferent_6727232360810837345(final ReferenceMacroContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "sm_ref", false), "content", true), "statements", true), "USML.structure.PutEventBinding")).first(), "cbinding", true), "var", false);
  }

  public static Object referenceMacro_GetReferent_6727232360810998509(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(SLinkOperations.getTarget(_context.getNode(), "sm_ref", false), "cur_thread_for_sm");
  }

  public static Object referenceMacro_GetReferent_7466645974728471287(final ReferenceMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object referenceMacro_GetReferent_7466645974728471306(final ReferenceMacroContext _context) {
    return "arg" + SNodeOperations.getIndexInParent(_context.getNode());
  }

  public static Object referenceMacro_GetReferent_7466645974728471347(final ReferenceMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(_context.getNode(), "eventRef", false), "virtual_id_3372386639989961954", new Object[]{});
  }

  public static boolean ifMacro_Condition_3946458319588738100(final IfMacroContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).isNotEmpty();
  }

  public static boolean ifMacro_Condition_3946458319589585241(final IfMacroContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).isNotEmpty();
  }

  public static boolean ifMacro_Condition_3946458319593005737(final IfMacroContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).isNotEmpty();
  }

  public static boolean ifMacro_Condition_8607120610932545246(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).isNotEmpty();
  }

  public static boolean ifMacro_Condition_8607120610928009741(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).isNotEmpty();
  }

  public static boolean ifMacro_Condition_7466645974728471180(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).isNotEmpty();
  }

  public static boolean ifMacro_Condition_7466645974728471193(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "actuals", true)).isNotEmpty();
  }

  public static SNode sourceNodeQuery_1054945346931916891(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "arg", false), "type", true);
  }

  public static SNode sourceNodeQuery_7466645974721995946(final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_3946458319588155114(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_3946458319588412227(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "init", true);
  }

  public static SNode sourceNodeQuery_3587558110351009863(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "init", true);
  }

  public static SNode sourceNodeQuery_7466645974685609247(final SourceSubstituteMacroNodeContext _context) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_action_2486662774780450342", new Object[]{});
  }

  public static SNode sourceNodeQuery_3946458319598746777(final SourceSubstituteMacroNodeContext _context) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_guard_2486662774780313941", new Object[]{});
  }

  public static SNode sourceNodeQuery_3174948071969274292(final SourceSubstituteMacroNodeContext _context) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), _context.getNode(), "virtual_guard_2486662774780313941", new Object[]{});
  }

  public static SNode sourceNodeQuery_8607120610930637856(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.CreateEventInstance", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static SNode sourceNodeQuery_8607120610930738178(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.CreateEventInstance", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static SNode sourceNodeQuery_8607120610931192699(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.CreateEventInstance", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static SNode sourceNodeQuery_6727232360811614611(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "sm_ref", false);
  }

  public static SNode sourceNodeQuery_7466645974728471205(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.EventCall", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static SNode sourceNodeQuery_7466645974728471226(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.EventCall", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static SNode sourceNodeQuery_7466645974728471247(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(ListSequence.fromList(BehaviorReflection.invokeVirtual((Class<List<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.EventCall", false, false), "virtual_getFormals_8011039602902827397", new Object[]{})).getElement(SNodeOperations.getIndexInParent(_context.getNode())), "type", true);
  }

  public static Iterable<SNode> sourceNodesQuery_130687814474693165(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IEvent", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_130687814474728624(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.StateLocalDeclaration", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319585698599(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.IRegion", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319587609673(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.RegionLocalDeclaration", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319588070023(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedOthers_4306907833977812919", new Object[]{}), "com.mbeddr.core.statements.structure.LocalVariableDeclaration");
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319598351314(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319588240198(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedOthers_4306907833977812919", new Object[]{}), "com.mbeddr.core.statements.structure.LocalVariableDeclaration")).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return !(SPropertyOperations.getBoolean(it, "static")) && (SLinkOperations.getTarget(it, "init", true) != null);
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319588752020(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).first(), "content", true), "statements", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319587493740(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.RegionLocalDeclaration", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319589585255(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).first(), "content", true), "statements", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319597947077(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319589585275(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.StateLocalDeclaration", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319593005751(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(Sequence.fromIterable(SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "content", true), "statements", true), "USML.structure.EntryBlock")).first(), "content", true), "statements", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319598022295(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3587558110351009890(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(SNodeOperations.ofConcept(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedOthers_4306907833977812919", new Object[]{}), "com.mbeddr.core.statements.structure.LocalVariableDeclaration")).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return (SLinkOperations.getTarget(it, "init", true) != null) && SPropertyOperations.getBoolean(it, "static");
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_3587558110353413860(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedStates_5600653557317358696", new Object[]{})).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), it, "virtual_getContainedRegions_3372386639992781270", new Object[]{});
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_3587558110351009968(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.RegionLocalDeclaration", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3587558110351010135(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_7466645974685408400(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.getDescendants(_context.getNode(), "USML.structure.ITransition", false, new String[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3372386639992189528(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3372386639992182519(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedStates_5600653557317358696", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319598746797(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_getContainedTransitions_2486662774781139473", new Object[]{})).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), it, "virtual_triggers_2486662774780450416", new Object[]{})).isNotEmpty() && BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), it, "virtual_source_2486662774780451176", new Object[]{}) == _context.getNode();
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_3946458319598746896(final SourceSubstituteMacroNodesContext _context) {
    return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getNode(), "USML.structure.IRegion", false, false), "virtual_getContainedTransitions_2486662774781139473", new Object[]{})).where(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), it, "virtual_triggers_2486662774780450416", new Object[]{})).isEmpty();
      }
    });
  }

  public static Iterable<SNode> sourceNodesQuery_3372386639991916520(final SourceSubstituteMacroNodesContext _context) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), _context.getNode(), "virtual_getContainedStates_5600653557317358696", new Object[]{});
  }

  public static Iterable<SNode> sourceNodesQuery_8607120610930595036(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8607120610930798927(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static Iterable<SNode> sourceNodesQuery_8607120610928009815(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static Iterable<SNode> sourceNodesQuery_7466645974728471265(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static Iterable<SNode> sourceNodesQuery_7466645974728471296(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static Iterable<SNode> sourceNodesQuery_7466645974728471327(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "actuals", true);
  }

  public static SNode weaving_MappingRule_ContextNodeQuery_3946458319584748846(final WeavingMappingRuleContext _context) {
    return _context.getCopiedOutputNodeForInputNode(SNodeOperations.getAncestor(_context.getNode(), "com.mbeddr.core.modules.structure.ImplementationModule", false, false));
  }
}
