package BSML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNodeReference;
import jetbrains.mps.smodel.SNodePointer;

public class CFunctionBinding_Constraints extends BaseConstraintsDescriptor {
  public CFunctionBinding_Constraints() {
    super("BSML.structure.CFunctionBinding");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("binding", new BaseReferenceConstraintsDescriptor("binding", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return SNodeOperations.ofConcept(SNodeOperations.getChildren(SNodeOperations.getAncestor(_context.getEnclosingNode(), "com.mbeddr.core.modules.structure.ImplementationModule", false, false)), "com.mbeddr.core.modules.structure.FunctionSignature");
          }

          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_qi6a6o_a0a1a0a0a1a0b0a1a1;
          }
        };
      }
    });
    return references;
  }

  private static SNodePointer breakingNode_qi6a6o_a0a1a0a0a1a0b0a1a1 = new SNodePointer("r:c262c7b2-132a-46e8-a5a7-0ff5b8b87a0c(BSML.constraints)", "8607120610933611281");
}
