package BSML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNodeReference;
import java.util.List;
import java.util.ArrayList;
import jetbrains.mps.internal.collections.runtime.Sequence;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.smodel.SNodePointer;

public class Transition_Constraints extends BaseConstraintsDescriptor {
  public Transition_Constraints() {
    super("BSML.structure.Transition");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("source", new BaseReferenceConstraintsDescriptor("source", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            // <node> 
            // <node> 
            return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.getAncestor(_context.getReferenceNode(), "BSML.structure.IStateScopeProvider", false, false), "virtual_getContainedStates_5600653557317358696", new Object[]{});
          }

          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_mgdfdy_a0a1a0a0a1a0b0a1a1;
          }
        };
      }
    });
    references.put("target", new BaseReferenceConstraintsDescriptor("target", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            final List<SNode> nodes = new ArrayList<SNode>();
            Sequence.fromIterable(SNodeOperations.ofConcept(SNodeOperations.getAncestors(_context.getReferenceNode(), null, false), "BSML.structure.IStateScopeProvider")).visitAll(new IVisitor<SNode>() {
              public void visit(SNode it) {
                ListSequence.fromList(nodes).addSequence(Sequence.fromIterable(BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), it, "virtual_getContainedStates_5600653557317358696", new Object[]{})));
              }
            });
            return nodes;
          }

          @Override
          public SNodeReference getSearchScopeValidatorNode() {
            return breakingNode_mgdfdy_a0a1a0a0a1a0b0a2a1;
          }
        };
      }
    });
    return references;
  }

  private static SNodePointer breakingNode_mgdfdy_a0a1a0a0a1a0b0a1a1 = new SNodePointer("r:c262c7b2-132a-46e8-a5a7-0ff5b8b87a0c(BSML.constraints)", "5600653557317358725");
  private static SNodePointer breakingNode_mgdfdy_a0a1a0a0a1a0b0a2a1 = new SNodePointer("r:c262c7b2-132a-46e8-a5a7-0ff5b8b87a0c(BSML.constraints)", "5600653557317919194");
}
