package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AbstractEventDeclaration_Behavior {
  public static void init(SNode thisNode) {
  }

  public static Iterable<SNode> virtual_args_2486662774781081797(SNode thisNode) {
    return SLinkOperations.getTargets(thisNode, "args", true);
  }

  public static Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return SLinkOperations.getTargets(thisNode, "args", true);
  }
}
