package BSML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CFunctionBinding_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CFunctionBinding_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.CFunctionBinding";
  }
}
