package BSML.behavior;

/*Generated by MPS */


public class EntryBlock_BehaviorDescriptor extends AbstractBlock_BehaviorDescriptor {
  public EntryBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.EntryBlock";
  }
}
