package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.udt.behavior.StructType_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;

public class EventType_BehaviorDescriptor extends StructType_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public EventType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.EventType";
  }
}
