package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.modules.behavior.ArgumentRef_BehaviorDescriptor;

public class EventArgReference_BehaviorDescriptor extends ArgumentRef_BehaviorDescriptor {
  public EventArgReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.EventArgReference";
  }
}
