package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IAbstrackBlockContainer_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedBlocks_3213732475053493833(SNode thisNode);
}
