package BSML.behavior;

/*Generated by MPS */


public class InEventDeclaration_BehaviorDescriptor extends AbstractEventDeclaration_BehaviorDescriptor {
  public InEventDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.InEventDeclaration";
  }
}
