package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IRegionScopeProvider_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static Iterable<SNode> call_getContainedRegions_3372386639992781270(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_getContainedRegions_3372386639992781270", new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> callSuper_getContainedRegions_3372386639992781270(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.IRegionScopeProvider"), callerConceptFqName, "virtual_getContainedRegions_3372386639992781270", new Class[]{SNode.class}, new Object[]{});
  }
}
