package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface ISMFullNameProvider_BehaviorDescriptor extends IIdentifierNamedConcept_BehaviorDescriptor {
  public String virtual_id_3372386639989961954(SNode thisNode);
}
