package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ISMFullNameProvider_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_id_3372386639989961954(SNode thisNode) {
    String full_name = IIdentifierNamedConcept_Behavior.call_qualifiedName_5470497459578244269(thisNode);
    return full_name.replaceAll("\\.", "__");
  }

  @Deprecated
  public static String call_id_3372386639989961954(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, thisNode, "virtual_id_3372386639989961954", new Object[]{});
  }

  @Deprecated
  public static String callSuper_id_3372386639989961954(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper(String.class, SNodeOperations.cast(thisNode, "BSML.structure.ISMFullNameProvider"), callerConceptFqName, "virtual_id_3372386639989961954", new Class[]{SNode.class}, new Object[]{});
  }
}
