package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface IState_BehaviorDescriptor extends ISMFullNameProvider_BehaviorDescriptor, IRegionScopeProvider_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
  public boolean virtual_isStable_8025659640029005022(SNode thisNode);
}
