package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ITransition_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static SNode call_guard_2486662774780313941(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_guard_2486662774780313941", new Object[]{});
  }

  @Deprecated
  public static SNode callSuper_guard_2486662774780313941(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.ITransition"), callerConceptFqName, "virtual_guard_2486662774780313941", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static SNode call_action_2486662774780450342(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_action_2486662774780450342", new Object[]{});
  }

  @Deprecated
  public static SNode callSuper_action_2486662774780450342(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.ITransition"), callerConceptFqName, "virtual_action_2486662774780450342", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static SNode call_target_2486662774780451200(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_target_2486662774780451200", new Object[]{});
  }

  @Deprecated
  public static SNode callSuper_target_2486662774780451200(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.ITransition"), callerConceptFqName, "virtual_target_2486662774780451200", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static SNode call_source_2486662774780451176(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<SNode>) ((Class) Object.class), thisNode, "virtual_source_2486662774780451176", new Object[]{});
  }

  @Deprecated
  public static SNode callSuper_source_2486662774780451176(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<SNode>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.ITransition"), callerConceptFqName, "virtual_source_2486662774780451176", new Class[]{SNode.class}, new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> call_triggers_2486662774780450416(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_triggers_2486662774780450416", new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> callSuper_triggers_2486662774780450416(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "BSML.structure.ITransition"), callerConceptFqName, "virtual_triggers_2486662774780450416", new Class[]{SNode.class}, new Object[]{});
  }
}
