package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface ITransitionProvider_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedTransitions_2486662774781139473(SNode thisNode);
}
