package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class SMSafeTerm_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public SMSafeTerm_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.SMSafeTerm";
  }
}
