package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class SMStart_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public SMStart_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.SMStart";
  }
}
