package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public class SMType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return 0;
  }
}
