package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class StateMachineConfigItem_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "debugMode", "" + (false));
    SPropertyOperations.set(thisNode, "generateTest", "" + (false));
  }
}
