package BSML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IConfigurationItem_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.base.behavior.ILOCCountProvider_Behavior;

public class StateMachineConfigItem_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IConfigurationItem_BehaviorDescriptor {
  public StateMachineConfigItem_BehaviorDescriptor() {
  }

  public SNode virtual_getConceptToBeCounted_7123462210703211996(SNode thisNode) {
    return ILOCCountProvider_Behavior.virtual_getConceptToBeCounted_7123462210703211996(thisNode);
  }

  public int virtual_getLOCEquivalent_7123462210702867712(SNode thisNode) {
    return ILOCCountProvider_Behavior.virtual_getLOCEquivalent_7123462210702867712(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.StateMachineConfigItem";
  }
}
