package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.LocalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_Behavior;

public class StateLocalDeclaration_BehaviorDescriptor extends LocalVariableDeclaration_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor, IState_BehaviorDescriptor, IContainsStatementList_BehaviorDescriptor, IContainerOfUniqueNames_BehaviorDescriptor, IAbstrackBlockContainer_BehaviorDescriptor {
  public StateLocalDeclaration_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_getContainedBlocks_3213732475053493833(SNode thisNode) {
    return StateLocalDeclaration_Behavior.virtual_getContainedBlocks_3213732475053493833(thisNode);
  }

  public Iterable<SNode> virtual_getContainedRegions_3372386639992781270(SNode thisNode) {
    return StateLocalDeclaration_Behavior.virtual_getContainedRegions_3372386639992781270(thisNode);
  }

  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return StateLocalDeclaration_Behavior.virtual_getUniquelyNamedElements_5095889050031059923(thisNode);
  }

  public String virtual_id_3372386639989961954(SNode thisNode) {
    return ISMFullNameProvider_Behavior.virtual_id_3372386639989961954(thisNode);
  }

  public boolean virtual_isStatementListCompact_1237546693016(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompact_1237546693016(thisNode);
  }

  public boolean virtual_isStatementListCompactable_1237546012856(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompactable_1237546012856(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.StateLocalDeclaration";
  }
}
