package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class StateLocalDeclaration_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "type", SConceptOperations.createNewNode("BSML.structure.StateType", null), true);
    SLinkOperations.setNewChild(thisNode, "content", "com.mbeddr.core.statements.structure.StatementList");
  }

  public static Iterable<SNode> virtual_getContainedRegions_3372386639992781270(SNode thisNode) {
    return SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true), "BSML.structure.IRegion");
  }

  public static Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return IRegionScopeProvider_Behavior.call_getContainedRegions_3372386639992781270(thisNode);
  }

  public static Iterable<SNode> virtual_getContainedBlocks_3213732475053493833(SNode thisNode) {
    return SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true), "BSML.structure.AbstractBlock");
  }
}
