package BSML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class StateType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public StateType_BehaviorDescriptor() {
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return StateType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "BSML.structure.StateType";
  }
}
