package BSML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class Transition_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "guard", SConceptOperations.createNewNode("com.mbeddr.core.expressions.structure.TrueLiteral", null), true);
  }

  public static SNode virtual_action_2486662774780450342(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "action", true);
  }

  public static SNode virtual_guard_2486662774780313941(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "guard", true);
  }

  public static SNode virtual_source_2486662774780451176(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "source", false);
  }

  public static SNode virtual_target_2486662774780451200(SNode thisNode) {
    return SLinkOperations.getTarget(thisNode, "target", false);
  }

  public static Iterable<SNode> virtual_triggers_2486662774780450416(SNode thisNode) {
    return ListSequence.fromList(SLinkOperations.getTargets(thisNode, "triggers", true)).select(new ISelector<SNode, SNode>() {
      public SNode select(SNode it) {
        return SLinkOperations.getTarget(it, "var", false);
      }
    });
  }
}
