package USML.util;

/*Generated by MPS */


public class util {
  public static String genStateEnumName(String id) {
    return id + "_StateEnum";
  }

  public static String genRegionStructName(String id) {
    return id + "_RegionStruct";
  }

  public static String genSMStructName(String id) {
    return id + "_SMStruct";
  }

  public static String genRegionEnumName(String id) {
    return id + "_RegionEnum";
  }

  public static String genEventEnumName(String id) {
    return id + "_EventEnum";
  }

  public static String genMessageListName(String id) {
    return "sm_msg_" + id;
  }

  public static String genBigStepFunctionName(String id) {
    return "execute_big_step_" + id;
  }

  public static String genSMStartFunctionName(String id) {
    return "sm_start_" + id;
  }

  public static String genPresentEventArrayName(String id) {
    return "present_event_" + id;
  }

  public static String genSMInfoName(String id) {
    return "sm_info_" + id;
  }
}
