package USML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum EventLifelineEnum {
  IN_REMAINDER("IN REMAINDER", 0),
  IN_NEXT_COMBO("IN NEXT COMBO", 1),
  IN_NEXT_SMALL("IN NEXT SMALL", 2);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<EventLifelineEnum> getConstants() {
    List<EventLifelineEnum> list = ListSequence.fromList(new LinkedList<EventLifelineEnum>());
    ListSequence.fromList(list).addElement(EventLifelineEnum.IN_REMAINDER);
    ListSequence.fromList(list).addElement(EventLifelineEnum.IN_NEXT_COMBO);
    ListSequence.fromList(list).addElement(EventLifelineEnum.IN_NEXT_SMALL);
    return list;
  }

  public static EventLifelineEnum getDefault() {
    return EventLifelineEnum.IN_REMAINDER;
  }

  public static EventLifelineEnum parseValue(String value) {
    if (value == null) {
      return EventLifelineEnum.getDefault();
    }
    if (value.equals(EventLifelineEnum.IN_REMAINDER.getValueAsString())) {
      return EventLifelineEnum.IN_REMAINDER;
    }
    if (value.equals(EventLifelineEnum.IN_NEXT_COMBO.getValueAsString())) {
      return EventLifelineEnum.IN_NEXT_COMBO;
    }
    if (value.equals(EventLifelineEnum.IN_NEXT_SMALL.getValueAsString())) {
      return EventLifelineEnum.IN_NEXT_SMALL;
    }
    return EventLifelineEnum.getDefault();
  }

  private int myValue;

  EventLifelineEnum(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
