package USML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum VariableLifeline {
  STRONG_SYNC("STRONG SYNC", 0),
  WEAK_SYNC("WEAK SYNC", 1),
  ASYNC("ASYNC", 2);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<VariableLifeline> getConstants() {
    List<VariableLifeline> list = ListSequence.fromList(new LinkedList<VariableLifeline>());
    ListSequence.fromList(list).addElement(VariableLifeline.STRONG_SYNC);
    ListSequence.fromList(list).addElement(VariableLifeline.WEAK_SYNC);
    ListSequence.fromList(list).addElement(VariableLifeline.ASYNC);
    return list;
  }

  public static VariableLifeline getDefault() {
    return VariableLifeline.STRONG_SYNC;
  }

  public static VariableLifeline parseValue(String value) {
    if (value == null) {
      return VariableLifeline.getDefault();
    }
    if (value.equals(VariableLifeline.STRONG_SYNC.getValueAsString())) {
      return VariableLifeline.STRONG_SYNC;
    }
    if (value.equals(VariableLifeline.WEAK_SYNC.getValueAsString())) {
      return VariableLifeline.WEAK_SYNC;
    }
    if (value.equals(VariableLifeline.ASYNC.getValueAsString())) {
      return VariableLifeline.ASYNC;
    }
    return VariableLifeline.getDefault();
  }

  private int myValue;

  VariableLifeline(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
