package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class AbstractBlock_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setNewChild(thisNode, "content", "com.mbeddr.core.statements.structure.StatementList");
    SLinkOperations.addNewChild(SLinkOperations.getTarget(thisNode, "content", true), "statements", "com.mbeddr.core.statements.structure.Statement");
  }
}
