package USML.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 18:
        return new SMType_BehaviorDescriptor();
      case 23:
        return new StateType_BehaviorDescriptor();
      case 15:
        return new SMGlobalDeclaration_BehaviorDescriptor();
      case 19:
        return new StateLocalDeclaration_BehaviorDescriptor();
      case 13:
        return new RegionLocalDeclaration_BehaviorDescriptor();
      case 14:
        return new RegionType_BehaviorDescriptor();
      case 9:
        return new InEventDeclaration_BehaviorDescriptor();
      case 11:
        return new OutEventDeclaration_BehaviorDescriptor();
      case 10:
        return new LocalEventDeclaration_BehaviorDescriptor();
      case 24:
        return new Transition_BehaviorDescriptor();
      case 4:
        return new EventArgReference_BehaviorDescriptor();
      case 6:
        return new EventType_BehaviorDescriptor();
      case 25:
        return new TransitionType_BehaviorDescriptor();
      case 5:
        return new EventCall_BehaviorDescriptor();
      case 21:
        return new StateMachineConfigItem_BehaviorDescriptor();
      case 3:
        return new EntryBlock_BehaviorDescriptor();
      case 7:
        return new ExitBlock_BehaviorDescriptor();
      case 2:
        return new DoBlock_BehaviorDescriptor();
      case 26:
        return new TriggerEventReference_BehaviorDescriptor();
      case 22:
        return new StateMachineSemanticsConfigItem_BehaviorDescriptor();
      case 1:
        return new CreateEventInstance_BehaviorDescriptor();
      case 20:
        return new StateMachineBindingsConfigItem_BehaviorDescriptor();
      case 0:
        return new CFunctionBinding_BehaviorDescriptor();
      case 8:
        return new GetEventBinding_BehaviorDescriptor();
      case 17:
        return new SMStart_BehaviorDescriptor();
      case 16:
        return new SMSafeTerm_BehaviorDescriptor();
      case 12:
        return new PutEventBinding_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }

  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"USML.structure.CFunctionBinding", "USML.structure.CreateEventInstance", "USML.structure.DoBlock", "USML.structure.EntryBlock", "USML.structure.EventArgReference", "USML.structure.EventCall", "USML.structure.EventType", "USML.structure.ExitBlock", "USML.structure.GetEventBinding", "USML.structure.InEventDeclaration", "USML.structure.LocalEventDeclaration", "USML.structure.OutEventDeclaration", "USML.structure.PutEventBinding", "USML.structure.RegionLocalDeclaration", "USML.structure.RegionType", "USML.structure.SMGlobalDeclaration", "USML.structure.SMSafeTerm", "USML.structure.SMStart", "USML.structure.SMType", "USML.structure.StateLocalDeclaration", "USML.structure.StateMachineBindingsConfigItem", "USML.structure.StateMachineConfigItem", "USML.structure.StateMachineSemanticsConfigItem", "USML.structure.StateType", "USML.structure.Transition", "USML.structure.TransitionType", "USML.structure.TriggerEventReference"};
}
