package USML.behavior;

/*Generated by MPS */


public class DoBlock_BehaviorDescriptor extends AbstractBlock_BehaviorDescriptor {
  public DoBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.DoBlock";
  }
}
