package USML.behavior;

/*Generated by MPS */


public class ExitBlock_BehaviorDescriptor extends AbstractBlock_BehaviorDescriptor {
  public ExitBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.ExitBlock";
  }
}
