package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class GetEventBinding_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public GetEventBinding_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.GetEventBinding";
  }
}
