package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IEventScopeProvider_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedEvents_2093108837558419581(SNode thisNode);
}
