package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface IEvent_BehaviorDescriptor extends ISMFullNameProvider_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
  public Iterable<SNode> virtual_args_2486662774781081797(SNode thisNode);
}
