package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;

public interface IStateMachine_BehaviorDescriptor extends ISMFullNameProvider_BehaviorDescriptor, IRegionScopeProvider_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
}
