package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IStateScopeProvider_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedStates_5600653557317358696(SNode thisNode);
}
