package USML.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface ITransition_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor, ISMFullNameProvider_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
  public SNode virtual_guard_2486662774780313941(SNode thisNode);
  public SNode virtual_action_2486662774780450342(SNode thisNode);
  public SNode virtual_target_2486662774780451200(SNode thisNode);
  public SNode virtual_source_2486662774780451176(SNode thisNode);
  public Iterable<SNode> virtual_triggers_2486662774780450416(SNode thisNode);
}
