package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.modules.behavior.GlobalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_Behavior;

public class SMGlobalDeclaration_BehaviorDescriptor extends GlobalVariableDeclaration_BehaviorDescriptor implements IStateMachine_BehaviorDescriptor, IContainsStatementList_BehaviorDescriptor, IContainerOfUniqueNames_BehaviorDescriptor {
  public SMGlobalDeclaration_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_getContainedRegions_3372386639992781270(SNode thisNode) {
    return SMGlobalDeclaration_Behavior.virtual_getContainedRegions_3372386639992781270(thisNode);
  }

  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return SMGlobalDeclaration_Behavior.virtual_getUniquelyNamedElements_5095889050031059923(thisNode);
  }

  public String virtual_id_3372386639989961954(SNode thisNode) {
    return ISMFullNameProvider_Behavior.virtual_id_3372386639989961954(thisNode);
  }

  public boolean virtual_isStatementListCompact_1237546693016(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompact_1237546693016(thisNode);
  }

  public boolean virtual_isStatementListCompactable_1237546012856(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompactable_1237546012856(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.SMGlobalDeclaration";
  }
}
