package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class SMType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public SMType_BehaviorDescriptor() {
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return SMType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.SMType";
  }
}
