package USML.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class OutEventDeclaration_Constraints extends BaseConstraintsDescriptor {
  public OutEventDeclaration_Constraints() {
    super("USML.structure.OutEventDeclaration");
  }
}
