package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public abstract class AbstractEventDeclaration_BehaviorDescriptor extends Statement_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor, IEvent_BehaviorDescriptor, IContainerOfUniqueNames_BehaviorDescriptor {
  public AbstractEventDeclaration_BehaviorDescriptor() {
  }

  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowNonIdentifierNames_6584628407655574550(thisConcept);
  }

  public Iterable<SNode> virtual_args_2486662774781081797(SNode thisNode) {
    return AbstractEventDeclaration_Behavior.virtual_args_2486662774781081797(thisNode);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return AbstractEventDeclaration_Behavior.virtual_getUniquelyNamedElements_5095889050031059923(thisNode);
  }

  public String virtual_id_3372386639989961954(SNode thisNode) {
    return ISMFullNameProvider_Behavior.virtual_id_3372386639989961954(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.AbstractEventDeclaration";
  }
}
