package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;
import com.mbeddr.core.modules.behavior.ICallLike_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import java.util.List;
import com.mbeddr.core.modules.behavior.ICallLike_Behavior;

public class CreateEventInstance_BehaviorDescriptor extends Expression_BehaviorDescriptor implements ICallLike_BehaviorDescriptor {
  public CreateEventInstance_BehaviorDescriptor() {
  }

  public SNode virtual_getActualsLink_2963921682938640512(SConcept thisConcept) {
    return CreateEventInstance_Behavior.virtual_getActualsLink_2963921682938640512(thisConcept);
  }

  public List<SNode> virtual_getActuals_8011039602902827390(SNode thisNode) {
    return CreateEventInstance_Behavior.virtual_getActuals_8011039602902827390(thisNode);
  }

  public String virtual_getFormalsAsString_9122562988443846072(SNode thisNode) {
    return ICallLike_Behavior.virtual_getFormalsAsString_9122562988443846072(thisNode);
  }

  public List<SNode> virtual_getFormals_8011039602902827397(SNode thisNode) {
    return CreateEventInstance_Behavior.virtual_getFormals_8011039602902827397(thisNode);
  }

  public SNode virtual_getNodeForTypeCalc_8729127847821610916(SNode thisNode) {
    return CreateEventInstance_Behavior.virtual_getNodeForTypeCalc_8729127847821610916(thisNode);
  }

  public boolean virtual_hasEllipsis_8729127847821611677(SNode thisNode) {
    return ICallLike_Behavior.virtual_hasEllipsis_8729127847821611677(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.CreateEventInstance";
  }
}
