package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IAbstrackBlockContainer_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static Iterable<SNode> call_getContainedBlocks_3213732475053493833(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_getContainedBlocks_3213732475053493833", new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> callSuper_getContainedBlocks_3213732475053493833(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "USML.structure.IAbstrackBlockContainer"), callerConceptFqName, "virtual_getContainedBlocks_3213732475053493833", new Class[]{SNode.class}, new Object[]{});
  }
}
