package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.ILocalVarScopeProvider_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface IRegion_BehaviorDescriptor extends ISMFullNameProvider_BehaviorDescriptor, ILocalVarScopeProvider_BehaviorDescriptor, IEventScopeProvider_BehaviorDescriptor, IStateScopeProvider_BehaviorDescriptor, ITransitionProvider_BehaviorDescriptor, IIdentifierNamedConcept_BehaviorDescriptor {
  public SNode virtual_initState_4306907833977380124(SNode thisNode);
  public Iterable<SNode> virtual_getContainedOthers_4306907833977812919(SNode thisNode);
}
