package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface IRegionScopeProvider_BehaviorDescriptor {
  public Iterable<SNode> virtual_getContainedRegions_3372386639992781270(SNode thisNode);
}
