package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class IStateScopeProvider_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static Iterable<SNode> call_getContainedStates_5600653557317358696(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_getContainedStates_5600653557317358696", new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> callSuper_getContainedStates_5600653557317358696(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "USML.structure.IStateScopeProvider"), callerConceptFqName, "virtual_getContainedStates_5600653557317358696", new Class[]{SNode.class}, new Object[]{});
  }
}
