package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.smodel.behaviour.BehaviorManager;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class ITransitionProvider_Behavior {
  public static void init(SNode thisNode) {
  }

  @Deprecated
  public static Iterable<SNode> call_getContainedTransitions_2486662774781139473(SNode thisNode) {
    return BehaviorReflection.invokeVirtual((Class<Iterable<SNode>>) ((Class) Object.class), thisNode, "virtual_getContainedTransitions_2486662774781139473", new Object[]{});
  }

  @Deprecated
  public static Iterable<SNode> callSuper_getContainedTransitions_2486662774781139473(SNode thisNode, String callerConceptFqName) {
    return BehaviorManager.getInstance().invokeSuper((Class<Iterable<SNode>>) ((Class) Object.class), SNodeOperations.cast(thisNode, "USML.structure.ITransitionProvider"), callerConceptFqName, "virtual_getContainedTransitions_2486662774781139473", new Class[]{SNode.class}, new Object[]{});
  }
}
