package USML.behavior;

/*Generated by MPS */


public class LocalEventDeclaration_BehaviorDescriptor extends AbstractEventDeclaration_BehaviorDescriptor {
  public LocalEventDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.LocalEventDeclaration";
  }
}
