package USML.behavior;

/*Generated by MPS */


public class OutEventDeclaration_BehaviorDescriptor extends AbstractEventDeclaration_BehaviorDescriptor {
  public OutEventDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.OutEventDeclaration";
  }
}
