package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;

public class PutEventBinding_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public PutEventBinding_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.PutEventBinding";
  }
}
