package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.LocalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_BehaviorDescriptor;
import com.mbeddr.core.base.behavior.IContainerOfUniqueNames_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import com.mbeddr.core.statements.behavior.LocalVarScope;
import jetbrains.mps.baseLanguage.behavior.IContainsStatementList_Behavior;

public class RegionLocalDeclaration_BehaviorDescriptor extends LocalVariableDeclaration_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor, IRegion_BehaviorDescriptor, IContainsStatementList_BehaviorDescriptor, IContainerOfUniqueNames_BehaviorDescriptor, IAbstrackBlockContainer_BehaviorDescriptor {
  public RegionLocalDeclaration_BehaviorDescriptor() {
  }

  public Iterable<SNode> virtual_getContainedBlocks_3213732475053493833(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedBlocks_3213732475053493833(thisNode);
  }

  public Iterable<SNode> virtual_getContainedEvents_2093108837558419581(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedEvents_2093108837558419581(thisNode);
  }

  public Iterable<SNode> virtual_getContainedLocalVariables_2093108837558419581(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedLocalVariables_2093108837558419581(thisNode);
  }

  public Iterable<SNode> virtual_getContainedOthers_4306907833977812919(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedOthers_4306907833977812919(thisNode);
  }

  public Iterable<SNode> virtual_getContainedStates_5600653557317358696(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedStates_5600653557317358696(thisNode);
  }

  public Iterable<SNode> virtual_getContainedTransitions_2486662774781139473(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getContainedTransitions_2486662774781139473(thisNode);
  }

  public LocalVarScope virtual_getLocalVarScope_2093108837558189309(SNode thisNode, SNode context, int statementIndex) {
    return RegionLocalDeclaration_Behavior.virtual_getLocalVarScope_2093108837558189309(thisNode, context, statementIndex);
  }

  public Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_getUniquelyNamedElements_5095889050031059923(thisNode);
  }

  public String virtual_id_3372386639989961954(SNode thisNode) {
    return ISMFullNameProvider_Behavior.virtual_id_3372386639989961954(thisNode);
  }

  public SNode virtual_initState_4306907833977380124(SNode thisNode) {
    return RegionLocalDeclaration_Behavior.virtual_initState_4306907833977380124(thisNode);
  }

  public boolean virtual_isStatementListCompact_1237546693016(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompact_1237546693016(thisNode);
  }

  public boolean virtual_isStatementListCompactable_1237546012856(SNode thisNode) {
    return IContainsStatementList_Behavior.virtual_isStatementListCompactable_1237546012856(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.RegionLocalDeclaration";
  }
}
