package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class RegionType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public RegionType_BehaviorDescriptor() {
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return RegionType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.RegionType";
  }
}
