package USML.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class SMGlobalDeclaration_Behavior {
  public static void init(SNode thisNode) {
    SLinkOperations.setTarget(thisNode, "type", SConceptOperations.createNewNode("USML.structure.SMType", null), true);
    SLinkOperations.setNewChild(thisNode, "content", "com.mbeddr.core.statements.structure.StatementList");
    ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true)).addElement(SConceptOperations.createNewNode("USML.structure.GetEventBinding", null));
    ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true)).addElement(SConceptOperations.createNewNode("USML.structure.PutEventBinding", null));
    ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true)).addElement(SConceptOperations.createNewNode("USML.structure.RegionLocalDeclaration", null));
  }

  public static Iterable<SNode> virtual_getContainedRegions_3372386639992781270(SNode thisNode) {
    return SNodeOperations.ofConcept(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "content", true), "statements", true), "USML.structure.IRegion");
  }

  public static Iterable<SNode> virtual_getUniquelyNamedElements_5095889050031059923(SNode thisNode) {
    return IRegionScopeProvider_Behavior.call_getContainedRegions_3372386639992781270(thisNode);
  }
}
