package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.statements.behavior.Statement_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import com.mbeddr.core.base.behavior.IIdentifierNamedConcept_Behavior;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Transition_BehaviorDescriptor extends Statement_BehaviorDescriptor implements ITransition_BehaviorDescriptor {
  public Transition_BehaviorDescriptor() {
  }

  public SNode virtual_action_2486662774780450342(SNode thisNode) {
    return Transition_Behavior.virtual_action_2486662774780450342(thisNode);
  }

  public boolean virtual_allowNonIdentifierNames_6584628407655574550(SConcept thisConcept) {
    return IIdentifierNamedConcept_Behavior.virtual_allowNonIdentifierNames_6584628407655574550(thisConcept);
  }

  public String virtual_conceptLabel_5470497459580078362(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_conceptLabel_5470497459580078362(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public SNode virtual_guard_2486662774780313941(SNode thisNode) {
    return Transition_Behavior.virtual_guard_2486662774780313941(thisNode);
  }

  public String virtual_id_3372386639989961954(SNode thisNode) {
    return ISMFullNameProvider_Behavior.virtual_id_3372386639989961954(thisNode);
  }

  public String virtual_qualifiedName_5470497459578244269(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_qualifiedName_5470497459578244269(thisNode);
  }

  public String virtual_shortDescriptionForCCMenu_5470497459578304992(SNode thisNode) {
    return IIdentifierNamedConcept_Behavior.virtual_shortDescriptionForCCMenu_5470497459578304992(thisNode);
  }

  public SNode virtual_source_2486662774780451176(SNode thisNode) {
    return Transition_Behavior.virtual_source_2486662774780451176(thisNode);
  }

  public SNode virtual_target_2486662774780451200(SNode thisNode) {
    return Transition_Behavior.virtual_target_2486662774780451200(thisNode);
  }

  public Iterable<SNode> virtual_triggers_2486662774780450416(SNode thisNode) {
    return Transition_Behavior.virtual_triggers_2486662774780450416(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.Transition";
  }
}
