package USML.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Type_BehaviorDescriptor;
import jetbrains.mps.lang.core.behavior.IDontSubstituteByDefault_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class TransitionType_BehaviorDescriptor extends Type_BehaviorDescriptor implements IDontSubstituteByDefault_BehaviorDescriptor {
  public TransitionType_BehaviorDescriptor() {
  }

  public int virtual_getUsedBytes_6941595764870551407(SNode thisNode) {
    return TransitionType_Behavior.virtual_getUsedBytes_6941595764870551407(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "USML.structure.TransitionType";
  }
}
