package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum PriorityEnum {
  EXPLICIT("EXPLICIT", 0),
  HIERARCHICAL("HIERARCHICAL", 1);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<PriorityEnum> getConstants() {
    List<PriorityEnum> list = ListSequence.fromList(new LinkedList<PriorityEnum>());
    ListSequence.fromList(list).addElement(PriorityEnum.EXPLICIT);
    ListSequence.fromList(list).addElement(PriorityEnum.HIERARCHICAL);
    return list;
  }

  public static PriorityEnum getDefault() {
    return PriorityEnum.EXPLICIT;
  }

  public static PriorityEnum parseValue(String value) {
    if (value == null) {
      return PriorityEnum.getDefault();
    }
    if (value.equals(PriorityEnum.EXPLICIT.getValueAsString())) {
      return PriorityEnum.EXPLICIT;
    }
    if (value.equals(PriorityEnum.HIERARCHICAL.getValueAsString())) {
      return PriorityEnum.HIERARCHICAL;
    }
    return PriorityEnum.getDefault();
  }

  private int myValue;

  PriorityEnum(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
