package BSML.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum SmallStepConsistencyEnum {
  SOURCE_DESTINATION_ORTHOGONAL("SOURCE/DESTINATION ORTHOGONAL", 0),
  ARENA_ORTHOGONAL("ARENA ORTHOGONAL", 1);

  private String myName;

  public String getName() {
    return this.myName;
  }

  public String getValueAsString() {
    return "" + this.myValue;
  }

  public static List<SmallStepConsistencyEnum> getConstants() {
    List<SmallStepConsistencyEnum> list = ListSequence.fromList(new LinkedList<SmallStepConsistencyEnum>());
    ListSequence.fromList(list).addElement(SmallStepConsistencyEnum.SOURCE_DESTINATION_ORTHOGONAL);
    ListSequence.fromList(list).addElement(SmallStepConsistencyEnum.ARENA_ORTHOGONAL);
    return list;
  }

  public static SmallStepConsistencyEnum getDefault() {
    return SmallStepConsistencyEnum.SOURCE_DESTINATION_ORTHOGONAL;
  }

  public static SmallStepConsistencyEnum parseValue(String value) {
    if (value == null) {
      return SmallStepConsistencyEnum.getDefault();
    }
    if (value.equals(SmallStepConsistencyEnum.SOURCE_DESTINATION_ORTHOGONAL.getValueAsString())) {
      return SmallStepConsistencyEnum.SOURCE_DESTINATION_ORTHOGONAL;
    }
    if (value.equals(SmallStepConsistencyEnum.ARENA_ORTHOGONAL.getValueAsString())) {
      return SmallStepConsistencyEnum.ARENA_ORTHOGONAL;
    }
    return SmallStepConsistencyEnum.getDefault();
  }

  private int myValue;

  SmallStepConsistencyEnum(String name, int value) {
    this.myName = name;
    this.myValue = value;
  }

  public int getValue() {
    return this.myValue;
  }
}
