package BSML.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_SMTrigger_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_SMTrigger_InferenceRule() {
  }

  public void applyRule(final SNode smTrigger, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    SNode ptr_type = SConceptOperations.createNewNode("com.mbeddr.core.pointers.structure.PointerType", null);
    SLinkOperations.setTarget(ptr_type, "baseType", SConceptOperations.createNewNode("BSML.structure.EventType", null), true);
    {
      SNode _nodeToCheck_1029348928467 = smTrigger;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:4175e96b-4bf8-489b-b72c-d9eeeddab49d(BSML.typesystem)", "1054945346924183744", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:4175e96b-4bf8-489b-b72c-d9eeeddab49d(BSML.typesystem)", "1054945346924180508", true), (SNode) typeCheckingContext.typeOf(ptr_type, "r:4175e96b-4bf8-489b-b72c-d9eeeddab49d(BSML.typesystem)", "8607120610926933418", true), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "BSML.structure.CreateEventInstance";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConcept().getQualifiedName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
