package small_test.behavior;

/*Generated by MPS */

import com.mbeddr.core.expressions.behavior.Expression_BehaviorDescriptor;

public class HelloString_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public HelloString_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "small_test.structure.HelloString";
  }
}
